name: Version and Changelog on PR

on:
  pull_request:
    branches: [main]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 10.8.0
      - run: pnpm install
      - run: pnpm changeset version
      - run: pnpm build
      - name: Clean up changeset files
        run: |
          # Remove all .md files from .changeset directory (except README.md and config.json)
          find .changeset -name "*.md" ! -name "README.md" -delete
      - name: Commit and push version/changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json CHANGELOG.md
          git add -f dist/
          git add .changeset/ || true
          git commit -m "chore: version bump and changelog [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
